# Generated by Django 3.0.6 on 2020-05-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
